chore: suppress pre_commit errors (#424)
pre_commit.ci said:

Flake8...................................................................Failed
- hook id: flake8
- exit code: 1

src/api/flaskr/common/config.py:45:5: F824 `global __INSTANCE__` is unused: name is never assigned in scope
src/api/flaskr/dao/__init__.py:62:9: F824 `global redis_client` is unused: name is never assigned in scope
src/api/flaskr/framework/plugin/plugin_manager.py:104:9: F824 `global plugin_manager` is unused: name is never assigned in scope
src/api/flaskr/service/scenario/block_funcs.py:22:1: F811 redefinition of unused 'get_original_outline_tree' from line 11
src/api/flaskr/service/scenario/unit_funcs.py:91:56: E226 missing whitespace around arithmetic operator
src/api/flaskr/service/user/common.py:577:1: F811 redefinition of unused 'init_first_course' from line 554
src/api/flaskr/service/user/utils.py:116:17: F841 local variable 'remaining_time' is assigned to but never used
src/api/flaskr/service/user/utils.py:174:17: F841 local variable 'remaining_time' is assigned to but never used
src/api/migrations/versions/b6cbcf622c0a_add_default_system_profiles.py:9:1: F401 'alembic.op' imported but unused
src/api/migrations/versions/b6cbcf622c0a_add_default_system_profiles.py:10:1: F401 'sqlalchemy as sa' imported but unused
src/api/migrations/versions/b6cbcf622c0a_add_default_system_profiles.py:19:1: F401 'flask.Flask' imported but unused